// import './gulp/tasks/server.js';
// import './gulp/tasks/compressJs.js';
// import './gulp/tasks/html.js';
// import './gulp/tasks/img.js';
require('./gulp/tasks/css.js');
require('./gulp/tasks/watch.js');
require('./gulp/tasks/default.js');
// import './gulp/tasks/css.js';
// import './gulp/tasks/watch.js';
// import './gulp/tasks/default.js';